use migratus::domain::config::*;
use migratus::machine::builder::MigrationBuilder;
use std::fs;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== Migratus Test Runner ===\n");

    // Load configuration from JSON file
    let config_json = fs::read_to_string("test_data/config.json")?;
    let config: MigrationConfig = serde_json::from_str(&config_json)?;

    println!("✓ Configuration loaded");
    println!("  - Data source: {:?}", config.data_source);
    println!("  - Batch size: {}", config.batch_config.batch_size);
    println!("  - Output dir: {:?}\n", config.output_config.output_dir);

    // Initialize the migration builder
    let builder = MigrationBuilder::new(config);
    println!("✓ Migration builder created\n");

    // Step 1: Initialize
    println!("Step 1: Initializing...");
    let decision = builder.initialize()?;
    println!("✓ Initialization complete\n");

    // Step 2: Load/Merge data
    println!("Step 2: Loading data...");
    let validated = match decision {
        migratus::machine::builder::BranchDecision::RequiresMerge(b) => {
            println!("  - Merging customer and payment data...");
            b.merge().await?
        }
        migratus::machine::builder::BranchDecision::SkipMerge(b) => {
            println!("  - Loading pre-merged data...");
            b.load_merged_data().await?
        }
    };
    println!("✓ Data loaded\n");

    // Step 3: Validate
    println!("Step 3: Validating records...");
    let enriched = validated.validate().await?;
    println!("✓ Validation complete\n");

    // Step 4: Enrich
    println!("Step 4: Enriching with additional columns...");
    let columns = EnrichmentColumns::new();
    // Don't add line_number - it's auto-generated by the API

    let batched = enriched.enrich(columns).await?;
    println!("✓ Enrichment complete\n");

    // Step 5: Create batches
    println!("Step 5: Creating batches...");
    let migrated = batched.batch().await?;
    println!("✓ Batching complete\n");

    // Step 6: Migrate (this will call the API)
    println!("Step 6: Running migration...");
    println!("  ⚠️  This will make actual API calls!");
    println!("  - Make sure your API credentials are configured");
    println!("  - Check test_data/config.json\n");

    let completed = migrated.migrate().await?;
    println!("✓ Migration complete\n");

    // Step 7: Finalize
    println!("Step 7: Generating output files...");
    let output = completed.complete().await?;
    println!("✓ Output files generated\n");

    // Display summary
    println!("=== Migration Summary ===");
    println!(
        "Total input records:       {}",
        output.summary.total_input_records
    );
    println!(
        "Valid for migration:       {}",
        output.summary.valid_for_migration
    );
    println!(
        "Invalid (pre-migration):   {}",
        output.summary.invalid_pre_migration
    );
    println!(
        "Successful migrations:     {}",
        output.summary.successful_migrations
    );
    println!(
        "Failed migrations:         {}",
        output.summary.failed_migrations
    );
    println!(
        "Total output records:      {}",
        output.summary.total_output_records
    );
    println!("\nInvalid breakdown:");
    println!(
        "  - At merge stage:        {}",
        output.summary.invalid_at_merge
    );
    println!(
        "  - At validation stage:   {}",
        output.summary.invalid_at_validation
    );

    println!("\n=== Output Files ===");
    println!("Check the test_output/ directory for:");
    println!("  ✓ successful_migrations.csv");
    println!("  ✓ failed_migrations.csv");
    println!("  ✓ invalid_records.csv");
    println!("  ✓ batch_responses/*.json");

    Ok(())
}
